/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author yash
 */
public class BookCustomerOrder extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomerOrder
     */
    public BookCustomerOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprice = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        comboboxcatalog = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblorderitems = new javax.swing.JTable();
        txttotalprice = new javax.swing.JTextField();
        txtmycommission = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnsubmitorder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary            Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 56, 858, -1));

        jLabel2.setText("Activity: Book Customer Order");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 127, -1, -1));

        tblprice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Floor Price", "Cealing Price", "Target Price"
            }
        ));
        jScrollPane1.setViewportView(tblprice);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 561, 111));

        btnadd.setText("Add");
        add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, -1));

        comboboxcatalog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxcatalogActionPerformed(evt);
            }
        });
        add(comboboxcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setText("order items");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        tblorderitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Actual Price"
            }
        ));
        jScrollPane2.setViewportView(tblorderitems);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 560, 110));

        txttotalprice.setText("total price");
        add(txttotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        txtmycommission.setText("My Commission");
        txtmycommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmycommissionActionPerformed(evt);
            }
        });
        add(txtmycommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 130, -1));

        btncancel.setText("cancel");
        add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, -1, -1));

        btnsubmitorder.setText("submit order");
        add(btnsubmitorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxcatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxcatalogActionPerformed

    private void txtmycommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmycommissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmycommissionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsubmitorder;
    private javax.swing.JComboBox<String> comboboxcatalog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblorderitems;
    private javax.swing.JTable tblprice;
    private javax.swing.JTextField txtmycommission;
    private javax.swing.JTextField txttotalprice;
    // End of variables declaration//GEN-END:variables
}
