/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author yash
 */
public class SalesProductCatalog extends javax.swing.JPanel {

    /**
     * Creates new form SalesProductCatalog
     */
    public SalesProductCatalog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfindproductname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsalesproductcatalog = new javax.swing.JTable();
        comboboxcatalog = new javax.swing.JComboBox<>();
        btnnext = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary                        Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 977, 105));

        jLabel2.setText("Activity : Browse Product Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtfindproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindproductnameActionPerformed(evt);
            }
        });
        add(txtfindproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 160, -1));

        jLabel3.setText("Product Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jButton1.setText("Find>>");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, -1, -1));

        tblsalesproductcatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductID", "ProductName", "Targetprice", "Description"
            }
        ));
        jScrollPane1.setViewportView(tblsalesproductcatalog);
        if (tblsalesproductcatalog.getColumnModel().getColumnCount() > 0) {
            tblsalesproductcatalog.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 940, 240));

        comboboxcatalog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxcatalogActionPerformed(evt);
            }
        });
        add(comboboxcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 220, -1));

        btnnext.setText("next>>");
        add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtfindproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindproductnameActionPerformed

    private void comboboxcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxcatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxcatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JComboBox<String> comboboxcatalog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsalesproductcatalog;
    private javax.swing.JTextField txtfindproductname;
    // End of variables declaration//GEN-END:variables
}
