/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author yash
 */
public class SalesOrderStatus extends javax.swing.JPanel {

    /**
     * Creates new form SalesOrderStatus
     */
    public SalesOrderStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbegintime = new javax.swing.JTextField();
        txtendtime = new javax.swing.JTextField();
        btnfind = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btncheckstatus = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary                     Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 71, 934, -1));

        jLabel2.setText("Activity: Check Order Status");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 136, -1, -1));

        txtbegintime.setText("BeginTime");
        add(txtbegintime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtendtime.setText("EndTime");
        txtendtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtendtimeActionPerformed(evt);
            }
        });
        add(txtendtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnfind.setText("Find>>");
        add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel3.setText("TIME FRAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Date Started", "Date Completed", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 680, 180));

        btncheckstatus.setText("check status");
        add(btncheckstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtendtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtendtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtendtimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckstatus;
    private javax.swing.JButton btnfind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbegintime;
    private javax.swing.JTextField txtendtime;
    // End of variables declaration//GEN-END:variables
}
