/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.CustomerDirectory;
import BusinessPackage.Order;
import BusinessPackage.OrderItems;
import BusinessPackage.Product;
import BusinessPackage.Sales;
import BusinessPackage.Supplier;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class SalesBookCustomerOrder extends javax.swing.JPanel {

    /**
     * Creates new form SalesBookCustomerOrder
     */
    Business b;
    private JPanel userContainer;
    private Customer customer;
    Order order = new Order();
    private static int actualTotla = 0;
    Sales sales;
    ArrayList<Order> orderArray = new ArrayList<Order>();
    private static double commison = 0;

    public SalesBookCustomerOrder(JPanel userContainer, Business b, Customer customer, Sales sales) {
        initComponents();
        this.b = b;
        this.userContainer = userContainer;
        this.customer = customer;
        this.sales = sales;
        populateSupplierName();
        refreshOrderTable();
        sales.setBaseCompensation(1000);
    }

    public void populateSupplierName() {
        for (Supplier supplier : b.getSupplierCatalog().getSupplierDirectory()) {

            comboboxcatalog.addItem(supplier);

        }

    }

    public void refreshOrderTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblorderitems.getModel();
        defaultTableModel.setRowCount(0);
        for (OrderItems o : order.getOrderList()) {
            {

                Object[] row = new Object[5];
                row[0] = o.getProduct();
                row[1] = o.getProduct().getModelNum();
                row[2] = o.getActualPrice();

                defaultTableModel.addRow(row);

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprice = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        comboboxcatalog = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblorderitems = new javax.swing.JTable();
        txttotalprice = new javax.swing.JTextField();
        txtmycommission = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary            Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 858, -1));

        jLabel2.setText("Activity: Book Customer Order");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        tblprice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Floor Price", "Cealing Price", "Target Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblprice);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 561, 111));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        comboboxcatalog.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxcatalogItemStateChanged(evt);
            }
        });
        comboboxcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxcatalogActionPerformed(evt);
            }
        });
        add(comboboxcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 240, -1));

        jLabel3.setText("order items");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        tblorderitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Actual Price"
            }
        ));
        jScrollPane2.setViewportView(tblorderitems);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 560, 110));

        txttotalprice.setText("total price");
        add(txttotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 140, -1));

        txtmycommission.setText("My Commission");
        txtmycommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmycommissionActionPerformed(evt);
            }
        });
        add(txtmycommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 130, -1));

        btncancel.setText("cancel");
        add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, -1, -1));

        submitButton.setText("submit order");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        backButton.setText("Back<<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxcatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxcatalogActionPerformed

    private void txtmycommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmycommissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmycommissionActionPerformed

    private void comboboxcatalogItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxcatalogItemStateChanged
        // TODO add your handling code here:

        DefaultTableModel defaultTableModel = (DefaultTableModel) tblprice.getModel();
        defaultTableModel.setRowCount(0);
        Supplier sup = (Supplier) comboboxcatalog.getSelectedItem();
        for (Product p : sup.getProductCatalog().getProductList()) {
            {

                Object[] row = new Object[5];
                row[0] = p;
                row[1] = p.getModelNum();
                row[2] = p.getFloorPrice();
                row[3] = p.getCeilPrice();
                row[4] = p.getPrice();

                defaultTableModel.addRow(row);

            }


    }//GEN-LAST:event_comboboxcatalogItemStateChanged
    }
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        int selectedRows = tblprice.getSelectedRow();

        if (selectedRows < 0) {
            JOptionPane.showMessageDialog(null, "Select any row from the table to add the product", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            int actualPrice;
            Product product = (Product) tblprice.getValueAt(selectedRows, 0);
            if (customer.getMarket().getMarketName().equalsIgnoreCase("Student")) {
                actualPrice = product.getFloorPrice();
            } else {
                actualPrice = product.getCeilPrice();
            }
            actualTotla = actualTotla + product.getPrice() * Integer.parseInt(jSpinner1.getValue().toString());
            order.addOrderItem(product, Integer.parseInt(jSpinner1.getValue().toString()), actualPrice);
            order.setOrderStartDate(new Date());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy");
            String dateString = "11/11/2017";
            try {
                Date date = sdf.parse(dateString);
                order.setOrderEndDate(date);
                order.setOrderStatus("Sales Approved");

            } catch (ParseException ex) {
                Logger.getLogger(SalesBookCustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
            }

            refreshOrderTable();
        }
        txttotalprice.setText(String.valueOf(order.getOrderTotel()));

    }//GEN-LAST:event_addButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

        if (actualTotla > order.getOrderTotel()) {
            double diff = actualTotla - order.getOrderTotel();
            commison = Math.round(commison + (diff *(0.1)));
            txtmycommission.setText(String.valueOf(commison));
            double newRevenue = sales.getBaseCompensation() + commison;
            sales.setBaseCompensation(newRevenue);
        } else {
             double diff = order.getOrderTotel() - actualTotla ;
             txtmycommission.setText("No Commision Loss of"+diff);
             diff = diff + diff*(10/100);
         double newRevenue = sales.getBaseCompensation() - diff;
            sales.setBaseCompensation(newRevenue);
        }
        
        CustomerDirectory cusDir = sales.getCustomerDirectory();
        cusDir.addUser(customer);
        orderArray.add(order);
        customer.setOrderList(orderArray);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);

        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton btncancel;
    private javax.swing.JComboBox<Object> comboboxcatalog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable tblorderitems;
    private javax.swing.JTable tblprice;
    private javax.swing.JTextField txtmycommission;
    private javax.swing.JTextField txttotalprice;
    // End of variables declaration//GEN-END:variables
}
