/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.Order;
import BusinessPackage.Sales;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class SalesCommisionReviewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesCommisionReviewJPanel
     */
   Business b;
    private JPanel userContainer;

    Sales sales;

    public SalesCommisionReviewJPanel(JPanel userContainer, Business b, Sales sales) {
        initComponents();
        this.b = b;
        this.userContainer = userContainer;

        this.sales = sales;
        populateTable();
    }

    public void populateTable() {
          DefaultTableModel defaultTableModel = (DefaultTableModel) tableComiision.getModel();
        defaultTableModel.setRowCount(0);
                Object[] row = new Object[2];
                row[0] = sales.getFirstName();
                
                row[1] = sales.getCommision();

                defaultTableModel.addRow(row);

  
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableComiision = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableComiision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sales Name", "Commission"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableComiision);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 42, 731, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableComiision;
    // End of variables declaration//GEN-END:variables
}
