/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.Order;
import BusinessPackage.Sales;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ragha
 */
public class SalesManageCustomers extends javax.swing.JPanel {

    /**
     * Creates new form SalesManageCustomers
     */
    Business b;
    private JPanel userContainer;
    Sales sales;

    public SalesManageCustomers(JPanel userContainer, Business b, Sales sales) {
        initComponents();
        this.b = b;
        this.userContainer = userContainer;
        this.sales = sales;
        jLabel2.setText(sales.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerNameSearch = new javax.swing.JTextField();
        serveCustomerButton = new javax.swing.JButton();
        btnreviewsaleorderhistory = new javax.swing.JButton();
        btnreviewsalescommission = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterfacePackage/x1.png"))); // NOI18N
        jLabel1.setText("Xerox Sales Console ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 16, 650, 170));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, -1));
        add(customerNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 197, -1));

        serveCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serveCustomerButton.setText("Serve Customer <<");
        serveCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerButtonActionPerformed(evt);
            }
        });
        add(serveCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 320, -1));

        btnreviewsaleorderhistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreviewsaleorderhistory.setText("Review Sale Order History >>>");
        btnreviewsaleorderhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreviewsaleorderhistoryActionPerformed(evt);
            }
        });
        add(btnreviewsaleorderhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 320, -1));

        btnreviewsalescommission.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreviewsalescommission.setText("Review Sales Commission >>>");
        btnreviewsalescommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreviewsalescommissionActionPerformed(evt);
            }
        });
        add(btnreviewsalescommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 320, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setText("Logout");
        add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Monitor Sales Performance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void serveCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerButtonActionPerformed
        // TODO add your handling code here:
        Customer customer = b.getCustomerDirectory().findPersonByLastName(customerNameSearch.getText());
        if (customer != null) {
            ServeCustomerJPanel serveCustomerJPanel = new ServeCustomerJPanel(userContainer, b, customer, sales);
            userContainer.add("ServeCustomerJPanel", serveCustomerJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Customer isnt present in our DB ", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_serveCustomerButtonActionPerformed

    private void btnreviewsaleorderhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreviewsaleorderhistoryActionPerformed
        // TODO add your handling code here:
         SalesReviewOrderJPanel seReviewOrderJPanel = new SalesReviewOrderJPanel(userContainer, b, sales);
            userContainer.add("SalesReviewOrderJPanel", seReviewOrderJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);
      
    }//GEN-LAST:event_btnreviewsaleorderhistoryActionPerformed

    private void btnreviewsalescommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreviewsalescommissionActionPerformed
        // TODO add your handling code here:
          SalesCommisionReviewJPanel serCommisionReviewJPanel = new SalesCommisionReviewJPanel(userContainer, b, sales);
            userContainer.add("SalesCommisionReviewJPanel", serCommisionReviewJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);
    }//GEN-LAST:event_btnreviewsalescommissionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MonitorJPanel monitorJPanel = new MonitorJPanel(userContainer, b, sales);
            userContainer.add("MonitorJPanel", monitorJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreviewsaleorderhistory;
    private javax.swing.JButton btnreviewsalescommission;
    private javax.swing.JTextField customerNameSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton serveCustomerButton;
    // End of variables declaration//GEN-END:variables
}
