/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.Sales;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ragha
 */
public class SalesManageCustomers extends javax.swing.JPanel {

    /**
     * Creates new form SalesManageCustomers
     */
    Business b;
    private JPanel userContainer;
Sales sales;
    public SalesManageCustomers(JPanel userContainer, Business b,Sales sales) {
        initComponents();
        this.b = b;
        this.userContainer = userContainer;
        this.sales = sales;
        jLabel2.setText(sales.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerNameSearch = new javax.swing.JTextField();
        serveCustomerButton = new javax.swing.JButton();
        btnreviewsaleorderhistory = new javax.swing.JButton();
        btnreviewsalescommission = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        jLabel1.setText("Xerox Sales Console ");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Customer Name");

        serveCustomerButton.setText("Serve Customer <<");
        serveCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerButtonActionPerformed(evt);
            }
        });

        btnreviewsaleorderhistory.setText("Review Sale Order History >>>");
        btnreviewsaleorderhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreviewsaleorderhistoryActionPerformed(evt);
            }
        });

        btnreviewsalescommission.setText("Review Sales Commission >>>");
        btnreviewsalescommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreviewsalescommissionActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnreviewsalescommission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnreviewsaleorderhistory))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(btnlogout)))
                    .addComponent(serveCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(customerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(customerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(serveCustomerButton)
                .addGap(40, 40, 40)
                .addComponent(btnreviewsaleorderhistory)
                .addGap(48, 48, 48)
                .addComponent(btnreviewsalescommission)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(233, 233, 233))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serveCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerButtonActionPerformed
        // TODO add your handling code here:
        Customer customer = b.getCustomerDirectory().findPersonByLastName(customerNameSearch.getText());
         ServeCustomerJPanel serveCustomerJPanel = new ServeCustomerJPanel(userContainer,b,customer,sales);
                userContainer.add("ServeCustomerJPanel",serveCustomerJPanel);
                CardLayout cardLayout = (CardLayout) userContainer.getLayout();
                cardLayout.next(userContainer);
    }//GEN-LAST:event_serveCustomerButtonActionPerformed

    private void btnreviewsaleorderhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreviewsaleorderhistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreviewsaleorderhistoryActionPerformed

    private void btnreviewsalescommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreviewsalescommissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreviewsalescommissionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreviewsaleorderhistory;
    private javax.swing.JButton btnreviewsalescommission;
    private javax.swing.JTextField customerNameSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton serveCustomerButton;
    // End of variables declaration//GEN-END:variables
}
