/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.Order;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yash
 */
public class SalesOrderStatus extends javax.swing.JPanel {

    /**
     * Creates new form SalesOrderStatus
     */
    Business b;
    private JPanel userContainer;
    private Customer customer;

    public SalesOrderStatus(JPanel userContainer, Business b, Customer customer) {
        initComponents();
        this.b = b;
        this.userContainer = userContainer;
        this.customer = customer;
        populateOrder();
    }

    public void populateOrder() {

        DefaultTableModel defaultTableModel = (DefaultTableModel) orderTable.getModel();
        defaultTableModel.setRowCount(0);
        for (Order order : customer.getOrderList()) {

            Object[] row = new Object[4];
            row[0] = order.getOrderID();
            row[1] = order.getOrderStartDate();
            row[2] = order.getOrderEndDate();
            row[3] = order.getOrderStatus();

            defaultTableModel.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbegintime = new javax.swing.JTextField();
        txtendtime = new javax.swing.JTextField();
        btnfind = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btncheckstatus = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary                     Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 71, 934, -1));

        jLabel2.setText("Activity: Check Order Status");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 136, -1, -1));

        txtbegintime.setText("BeginTime");
        add(txtbegintime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtendtime.setText("EndTime");
        txtendtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtendtimeActionPerformed(evt);
            }
        });
        add(txtendtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnfind.setText("Find>>");
        add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel3.setText("TIME FRAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Date Started", "Date Completed", "Status"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 680, 180));

        btncheckstatus.setText("check status");
        add(btncheckstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));

        backButton.setText("Back<<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtendtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtendtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtendtimeActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);

        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btncheckstatus;
    private javax.swing.JButton btnfind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField txtbegintime;
    private javax.swing.JTextField txtendtime;
    // End of variables declaration//GEN-END:variables
}
