/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import BusinessPackage.Business;
import BusinessPackage.Customer;
import BusinessPackage.Product;
import BusinessPackage.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yash
 */
public class SalesProductCatalog extends javax.swing.JPanel {

    /**
     * Creates new form SalesProductCatalog
     */
    private JPanel userContainer;
    private Customer customer;
    private Business b;
    private Supplier supplier;
    
    
    
    
    public SalesProductCatalog( JPanel userContainer, Business b, Customer customer) {
        initComponents();
        this.userContainer = userContainer;
        this.customer= customer;
        this.b = b;
        
        populateSupplierName();
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfindproductname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsalesproductcatalog = new javax.swing.JTable();
        comboboxcatalog = new javax.swing.JComboBox<>();
        btnnext = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Information Summary                        Person Contact Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 977, 105));

        jLabel2.setText("Activity : Browse Product Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtfindproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindproductnameActionPerformed(evt);
            }
        });
        add(txtfindproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 160, -1));

        jLabel3.setText("Product Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jButton1.setText("Find>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, -1, -1));

        tblsalesproductcatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductName", "ProductID", "Targetprice", "Description"
            }
        ));
        jScrollPane1.setViewportView(tblsalesproductcatalog);
        if (tblsalesproductcatalog.getColumnModel().getColumnCount() > 0) {
            tblsalesproductcatalog.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 940, 240));

        comboboxcatalog.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxcatalogItemStateChanged(evt);
            }
        });
        comboboxcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxcatalogActionPerformed(evt);
            }
        });
        add(comboboxcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 220, -1));

        btnnext.setText("next>>");
        add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

      public void populateSupplierName() {
        for (Supplier supplier : b.getSupplierCatalog().getSupplierDirectory()) {

            comboboxcatalog.addItem(supplier);
            

        }

    }
    private void txtfindproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindproductnameActionPerformed

    private void comboboxcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxcatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxcatalogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        DefaultTableModel dtm=(DefaultTableModel) tblsalesproductcatalog.getModel();
        dtm.setRowCount(0);
        //System.out.println("UserInterface.ManageAirlines.ManageAirlinersWorkAreaJPanel.populateAirlinerTable()");
       // System.out.println("travel"+travelAgency.getAirlineDirectory());
       
        for(Supplier sup : b.getSupplierCatalog().getSupplierDirectory())
        {
            for(Product p : sup.getProductCatalog().getProductList())
            {
                if(p.getpName().equals(txtfindproductname.getText()))
                {
                    Object[] row=new Object[5];
            row[0]= p;
            //row[1]=a.getSerialNumber();
            row[1]=p.getModelNum();
            row[2]=p.getPrice();
            row[3]=p.getDescription();
            dtm.addRow(row);
                }
            }
        }
           
            
       if(dtm.getRowCount()<1)
           {
               JOptionPane.showMessageDialog(null,"No data Available for the entered details");
           }
            
            
        
                         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboboxcatalogItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxcatalogItemStateChanged
  DefaultTableModel defaultTableModel = (DefaultTableModel) tblsalesproductcatalog.getModel();
        defaultTableModel.setRowCount(0);
        Supplier sup = (Supplier) comboboxcatalog.getSelectedItem();
        for (Product p : sup.getProductCatalog().getProductList()) {
            {

                Object[] row = new Object[4];
                row[0] = p;
                row[1] = p.getModelNum();
                row[2] = p.getPrice();
                row[3]= p.getDescription();

                defaultTableModel.addRow(row);

            }
        }
    }//GEN-LAST:event_comboboxcatalogItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JComboBox<Object> comboboxcatalog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsalesproductcatalog;
    private javax.swing.JTextField txtfindproductname;
    // End of variables declaration//GEN-END:variables
}
